### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by jspickering** [wjchulme/OSWGmcr-MAPS-collaboration#12]
Hi all,

Can I suggest an in-person meeting to discuss everything and come up with an action plan? We can then create issues on github depending on what needs to be done

Jade

**Comment by lanabojanic** [comment]
Agreed. I am available from next week onwards, preferably in the afternoon.

**Comment by jspickering** [comment]
I'm free from Wednesday onwards

**Comment by jspickering** [comment]
@wjchulme @ajstewartlang @olijimbo ?
